export const guideSections=[
{slug:'personal-finance',label:'Personal Finance',groups:[['Budgeting',['Creating a budget','Common budgeting mistakes','Zero-based budgeting']],['Making Money',['Grow your money','Grow your savings','Where to invest']],['Managing Debt',['Pay off debt','Debt management plans']],['Credit Score',['What is a credit score?','Handling bad credit']]]},
{slug:'investing',label:'Investing',groups:[['Getting Started',['Investing basics','Risk and return','SIP and compounding']],['Investment Choices',['Mutual funds','Stocks and index funds','Gold and fixed deposits']],['Planning',['Build a diversified portfolio','Invest for long-term goals']]]},
{slug:'banking-guide',label:'Banking',groups:[['Everyday Banking',['Choosing a savings account','Emergency fund account','Digital banking safety']],['Smart Banking',['Avoid banking fees','Understand interest rates','Manage multiple accounts']]]},
{slug:'credit-cards',label:'Credit Cards',groups:[['Card Basics',['How credit cards work','Billing cycle and minimum due','Interest and late fees']],['Choosing Cards',['Choose the right credit card','Rewards versus annual fees','Use cards without debt']]]},
{slug:'loans',label:'Loans',groups:[['Personal Loans',['When a personal loan makes sense','Compare loan costs']],['Education Loans',['Student loan basics','Plan education repayment']],['Home & Vehicle',['Home-loan checklist','Car-loan affordability']]]},
{slug:'small-business',label:'Small Business',groups:[['Getting Started',['Separate business finances','Build a cash-flow plan']],['Growing',['Price for profit','Manage working capital','Save tax responsibly']]]},
{slug:'beginner-guides',label:'Beginner Guides',groups:[['Daily Money',['Save money in daily life','Weekly spending caps','Needs versus wants']],['First Steps',['Your first monthly plan','Build an emergency fund','Start investing with small amounts']]]}
];
const desc={'Creating a budget':'Build a realistic monthly plan around income, essentials, goals and flexible spending.','Common budgeting mistakes':'Fix unrealistic limits, forgotten irregular bills and plans that leave no breathing room.','Zero-based budgeting':'Give every rupee a purpose before the month begins.','Save money in daily life':'Use grocery lists, subscription audits, meal planning and a 24-hour purchase rule.','What is a credit score?':'Understand what a credit score represents and which habits affect it.','Handling bad credit':'Rebuild slowly through on-time payments, lower utilization and accurate records.'};
export const slugify=value=>value.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const images=['/images/finance-guide-cover.png','/images/guide-budgeting.png','/images/guide-investing.png','/images/guide-banking.png','/images/guide-loans-business.png'];
const imageFor=(section,group,index)=>section==='investing'?images[index%2?0:2]:section==='banking-guide'||section==='credit-cards'?images[index%2?3:0]:section==='loans'||section==='small-business'?images[index%2?4:1]:section==='personal-finance'?(group==='Budgeting'?images[index%2?1:0]:group==='Making Money'?images[index%2?2:1]:images[index%2?3:4]):images[index%images.length];
export const articles=guideSections.flatMap((section,s)=>section.groups.flatMap(([group,titles],g)=>titles.map((title,i)=>({slug:slugify(title),title,section:section.label,sectionSlug:section.slug,group,image:imageFor(section.slug,group,i),description:desc[title]||`A practical guide to ${title.toLowerCase()}, with simple decisions you can apply to your finances.`,readTime:`${4+((s+g+i)%5)} min read`,position:`${20+((s*17+g*23+i*13)%60)}% center`,steps:['Understand your current position before making changes.',`Set one measurable goal for ${title.toLowerCase()}.`,'Automate or schedule the next action.','Review the result every month and adjust.']}))));
