import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, ChevronLeft, ChevronRight, PiggyBank, Plus, Sparkles, TrendingDown, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from '../api/client';
import { categoryMap } from '../components/categoryConfig';
import { PageHeader, money } from '../components/UI';

export default function Dashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.get('/dashboard').then(({ data }) => setData(data)).catch(err => { if (err.response?.status !== 401) setError('Could not load your dashboard.'); }); }, []);
  if (error) return <div className="error">{error}</div>;
  if (!data) return <div className="loading">Preparing your overview…</div>;
  const forecastData = [...(data.forecast.history || []), ...(data.forecast.status === 'ready' ? [{ month: 'Next', predicted: data.forecast.next_month_total }] : [])];
  const summary = [
    { label:'Income', value:money(data.total_income), hint:'Received this month', icon:WalletCards, tone:'green' },
    { label:'Expenses', value:money(data.total_expenses), hint:'Spent this month', icon:TrendingDown, tone:'coral' },
    { label:'Savings', value:money(data.balance), hint:`${data.savings_rate}% savings rate`, icon:PiggyBank, tone:'blue' },
    { label:'Smart forecast', value:data.forecast.next_month_total?money(data.forecast.next_month_total):'Learning', hint:'Next month expenses', icon:Sparkles, tone:'violet' }
  ];
  return <><PageHeader eyebrow="SMART FINANCE" title="Your financial overview" description="Fast tracking with explainable analysis and forecasts."/>
    <section className="money-hero"><div className="period-switch"><button aria-label="Previous month"><ChevronLeft/></button><span>{data.month}</span><button aria-label="Next month" disabled><ChevronRight/></button></div><div className="money-hero-grid"><div className="balance-block"><span>Available balance</span><strong>{money(data.balance)}</strong><p className={data.balance>=0?'positive':'negative'}>{data.savings_rate}% savings rate this month</p><div className="quick-actions"><Link className="expense-action" to="/transactions?add=expense"><ArrowUpRight/>Add expense</Link><Link className="income-action" to="/transactions?add=income"><ArrowDownLeft/>Add income</Link></div></div><div className="donut-wrap">{data.by_category.length?<><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={data.by_category} dataKey="value" nameKey="name" innerRadius={86} outerRadius={125} paddingAngle={2}>{data.by_category.map(item=><Cell key={item.name} fill={categoryMap.get(item.name)?.color||'#849089'}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Expenses</small><strong>{money(data.total_expenses)}</strong></div></>:<div className="empty-donut"><Plus/><span>Add your first expense</span></div>}</div><div className="category-breakdown"><h2>Spending categories</h2>{data.by_category.slice(0,6).map(item=>{const config=categoryMap.get(item.name);const Icon=config?.icon;return <div key={item.name}><i style={{background:config?.color}}>{Icon?<Icon/>:item.name[0]}</i><span>{item.name}</span><strong>{money(item.value)}</strong></div>})}{!data.by_category.length?<p>No spending recorded this month.</p>:null}</div></div></section>
    <section className="bento-summary">{summary.map(({label,value,hint,icon:Icon,tone})=><article className={`bento-card ${tone}`} key={label}><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{hint}</p></div></article>)}</section>
    {data.alerts.length?<section className="dashboard-alerts">{data.alerts.map((alert,index)=><div className={`alert ${alert.level}`} key={`${alert.message}-${index}`}><AlertTriangle size={16}/>{alert.message}</div>)}</section>:null}
    <section className="analytics-heading"><div><p className="eyebrow">BEHAVIOR ANALYSIS</p><h2>Understand your habits</h2></div><Link to="/insights">View all insights →</Link></section>
    <section className="chart-grid"><article className="panel wide"><h2>Income and expenses</h2><p>Your monthly cash-flow pattern</p>{data.cashflow_trend.length?<ResponsiveContainer width="100%" height={270}><BarChart data={data.cashflow_trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={money}/><Legend/><Bar dataKey="income" fill="#48aa84" radius={[7,7,0,0]}/><Bar dataKey="expense" fill="#ef6c62" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer>:<div className="empty">Add transactions to see your cash flow.</div>}</article><article className="panel forecast-card"><span className="model-pill">LINEAR REGRESSION</span><h2>Next month outlook</h2><strong>{data.forecast.next_month_total?money(data.forecast.next_month_total):'Still learning'}</strong><p>{data.forecast.status==='ready'?'Uses rolling averages, seasonality, and known recurring expenses.':'Add expenses across four months for a reliable forecast.'}</p>{data.forecast.recurring_floor?<small>Known recurring floor: {money(data.forecast.recurring_floor)}</small>:null}{data.forecast.metrics?<div className="model-metrics"><span>MAE <b>{money(data.forecast.metrics.mae)}</b></span><span>RMSE <b>{money(data.forecast.metrics.rmse)}</b></span></div>:null}</article></section>
    <article className="panel forecast-panel"><h2>Predicted vs actual</h2><p>Compare the interpretable forecast with real spending</p>{forecastData.length?<ResponsiveContainer width="100%" height={290}><AreaChart data={forecastData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={money}/><Legend/><Area type="monotone" dataKey="actual" stroke="#26382f" fill="#48aa8430"/><Area type="monotone" dataKey="predicted" stroke="#ef6c62" fill="none" strokeDasharray="5 5"/></AreaChart></ResponsiveContainer>:<div className="empty">Four months of history are required for an honest forecast.</div>}</article>
  </>;
}
