import { ArrowRight,BookOpen,Clock,Lightbulb } from 'lucide-react';
import { Link,useParams,useSearchParams } from 'react-router-dom';
import { articles,guideSections } from '../content/guides';

export default function Learn(){
  const {sectionSlug='beginner-guides'}=useParams();const [params]=useSearchParams();
  const section=guideSections.find(x=>x.slug===sectionSlug)||guideSections[0];const selected=articles.find(x=>x.slug===params.get('article'));const cards=articles.filter(x=>x.sectionSlug===section.slug);
  if(selected)return <article className="article-reader"><Link to={`/learn/${section.slug}`}>← Back to {section.label}</Link><div className="article-hero"><img src={selected.image} style={{objectPosition:selected.position}}/><div><span>{selected.section} · {selected.group}</span><h1>{selected.title}</h1><p>{selected.description}</p><small><Clock/> {selected.readTime}</small></div></div><section><h2>A practical plan</h2>{selected.steps.map((step,i)=><div className="guide-step" key={step}><b>{i+1}</b><div><strong>{step}</strong><p>Keep it simple, record the result in Northstar, and use dashboard data instead of guessing.</p></div></div>)}<aside className="reader-tip"><Lightbulb/><p><strong>Northstar suggestion</strong><br/>Tag related spending consistently. Budget alerts and insights improve when your categories are accurate.</p></aside></section></article>;
  return <><header className="academy-hero"><p className="eyebrow">NORTHSTAR ACADEMY</p><h1>Money guidance for real life.</h1><p>Learn the idea, apply it daily, and measure the result in your dashboard.</p></header><section className="topic-strip">{section.groups.map(([group])=><span key={group}>{group}</span>)}</section><div className="guide-heading"><div><p className="eyebrow">{section.label}</p><h2>Recommended guides</h2></div><BookOpen/></div><section className="article-grid">{cards.map(card=><Link className="article-card" to={`/learn/${section.slug}?article=${card.slug}`} key={card.slug}><img src={card.image} style={{objectPosition:card.position}}/><div><span>{card.group}</span><h3>{card.title}</h3><p>{card.description}</p><footer><small>{card.readTime}</small><ArrowRight/></footer></div></Link>)}</section></>
}
