import { useEffect,useState } from 'react';
import { Landmark,LockKeyhole,LogOut,Mail,Receipt,ShieldCheck,UserRound } from 'lucide-react';
import api from '../api/client';
import { useAuth } from '../context/AuthContext';
import { AppLockSettings } from '../components/AppLock';
import { PageHeader } from '../components/UI';

export default function Profile(){
  const {user,updateUser,logout}=useAuth();const [stats,setStats]=useState({transactions:0,accounts:0});const [lockOpen,setLockOpen]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
  useEffect(()=>{Promise.all([api.get('/transactions'),api.get('/bank-accounts')]).then(([transactions,accounts])=>setStats({transactions:transactions.data.length,accounts:accounts.data.length}));},[]);
  const saveProfile=async event=>{event.preventDefault();setError('');try{const values=Object.fromEntries(new FormData(event.currentTarget));const {data}=await api.put('/auth/me',values);updateUser(data);setNotice('Profile updated successfully.');}catch(err){setError(err.response?.data?.detail||'Could not update profile.');}};
  const changePassword=async event=>{event.preventDefault();setError('');const values=Object.fromEntries(new FormData(event.currentTarget));if(values.new_password!==values.confirm_password){setError('New passwords do not match.');return;}try{await api.put('/auth/password',{current_password:values.current_password,new_password:values.new_password});event.currentTarget.reset();setNotice('Password changed successfully.');}catch(err){setError(err.response?.data?.detail||'Could not change password.');}};
  return <><PageHeader eyebrow="YOUR ACCOUNT" title="Profile & security" description="Manage your identity, password and finance workspace security."/>{notice?<div className="success">{notice}</div>:null}{error?<div className="error">{error}</div>:null}<section className="profile-hero"><div className="profile-avatar-large">{user.name[0].toUpperCase()}</div><div><h2>{user.name}</h2><p><Mail/> {user.email}</p></div><span className="profile-secure"><ShieldCheck/> Protected account</span></section><section className="profile-stats"><article><Receipt/><div><strong>{stats.transactions}</strong><span>Transactions</span></div></article><article><Landmark/><div><strong>{stats.accounts}</strong><span>Demo accounts</span></div></article><article><LockKeyhole/><div><strong>{user.app_lock_enabled?'On':'Off'}</strong><span>App lock</span></div></article></section><div className="profile-grid"><form className="panel profile-form" onSubmit={saveProfile}><span className="profile-form-icon"><UserRound/></span><h2>Personal information</h2><p>Used to personalize your Northstar workspace.</p><label>Full name<input name="name" defaultValue={user.name} minLength="2" required/></label><label>Email address<input name="email" type="email" defaultValue={user.email} required/></label><button className="primary">Save changes</button></form><form className="panel profile-form" onSubmit={changePassword}><span className="profile-form-icon"><LockKeyhole/></span><h2>Password & security</h2><p>Use at least eight characters for your account password.</p><label>Current password<input name="current_password" type="password" required/></label><label>New password<input name="new_password" type="password" minLength="8" required/></label><label>Confirm new password<input name="confirm_password" type="password" minLength="8" required/></label><button className="primary">Change password</button></form></div><section className="panel profile-actions"><div><h2>App lock</h2><p>Add a separate PIN when you step away from the device.</p></div><button className="secondary" onClick={()=>setLockOpen(true)}><LockKeyhole/>Manage app lock</button></section><button className="profile-logout" onClick={logout}><LogOut/>Sign out of Northstar</button>{lockOpen?<AppLockSettings onClose={()=>setLockOpen(false)}/>:null}</>;
}
