import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, Info, Plus, RefreshCw, Repeat2, Trash2, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import api from '../api/client';
import { categories, categoryMap } from '../components/categoryConfig';
import { Empty, money, PageHeader } from '../components/UI';

const today = new Date().toISOString().slice(0, 10);
const emptyDraft = { kind: 'expense', amount: '', description: '', occurred_on: today, is_recurring: false, currency: 'INR', bank_account_id: '' };

function QuickEntry({ initialKind = 'expense', onClose, onCreated }) {
  const [step,setStep]=useState(1); const [draft,setDraft]=useState(()=>({...emptyDraft,kind:initialKind})); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{api.get('/bank-accounts').then(({data})=>{if(data.length)setDraft(current=>({...current,bank_account_id:data[0].id}));});},[]);
  const update=(key,value)=>setDraft(current=>({...current,[key]:value}));
  const chooseCategory=async(category)=>{setSaving(true);setError('');try{await api.post('/transactions',{...draft,amount:Number(draft.amount),category:draft.kind==='expense'?category:undefined});await onCreated();onClose();}catch(err){setError(err.response?.data?.detail||'Could not save transaction.');setSaving(false);}};
  const next=(event)=>{event.preventDefault();if(!Number(draft.amount))return;if(draft.kind==='income')chooseCategory('Income');else setStep(2);};
  return <div className="quick-entry-backdrop" role="presentation"><section className="quick-entry" role="dialog" aria-modal="true" aria-labelledby="quick-entry-title"><header><button className="icon-button" onClick={step===1?onClose:()=>setStep(1)} aria-label={step===1?'Close':'Back'}>{step===1?<X/>:<ArrowLeft/>}</button><div><small>STEP {step} OF 2</small><h2 id="quick-entry-title">{step===1?'Enter amount':'Choose category'}</h2></div><span/></header>{step===1?<form onSubmit={next}><div className="kind-toggle"><button type="button" className={draft.kind==='expense'?'active expense':''} onClick={()=>update('kind','expense')}>Expense</button><button type="button" className={draft.kind==='income'?'active income':''} onClick={()=>update('kind','income')}>Income</button></div><div className="amount-entry"><select aria-label="Currency" value={draft.currency} onChange={event=>update('currency',event.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AED</option></select><input autoFocus aria-label="Amount" type="number" inputMode="decimal" min="0.01" step="0.01" required placeholder="0" value={draft.amount} onChange={event=>update('amount',event.target.value)}/></div><label>Optional note<input placeholder="What was this for?" maxLength="255" value={draft.description} onChange={event=>update('description',event.target.value)}/></label><div className="quick-options"><label><CalendarDays/><span>Date</span><input type="date" value={draft.occurred_on} onChange={event=>update('occurred_on',event.target.value)}/></label><label className="recurring-toggle"><Repeat2/><span>Recurring</span><input type="checkbox" checked={draft.is_recurring} onChange={event=>update('is_recurring',event.target.checked)}/></label></div><button className="primary next-button">{draft.kind==='income'?'Save income':'Choose category'} →</button></form>:<div className="category-step"><div className="entry-summary"><span>{draft.currency}</span><strong>{money(Number(draft.amount),draft.currency)}</strong><small>{draft.description||'No note added'}{draft.is_recurring?' · Recurring':''}</small></div><div className="category-picker">{categories.map(({name,icon:Icon,color,soft})=><button disabled={saving} key={name} onClick={()=>chooseCategory(name)} style={{'--category':color,'--category-soft':soft}}><span><Icon/></span><b>{name}</b></button>)}</div>{error?<div className="error">{error}</div>:null}</div>}</section></div>;
}

export default function Transactions() {
  const [searchParams,setSearchParams]=useSearchParams(); const requestedKind=searchParams.get('add');
  const [items,setItems]=useState([]); const [open,setOpen]=useState(()=>['expense','income'].includes(requestedKind)); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const load=()=>api.get('/transactions').then(({data})=>setItems(data));
  useEffect(()=>{load().catch(err=>{if(err.response?.status!==401)setError('Could not load transactions.');});},[]);
  const closeEntry=()=>{setOpen(false);setSearchParams({});};
  const remove=async(id)=>{await api.delete(`/transactions/${id}`);setItems(current=>current.filter(item=>item.id!==id));};
  const retrain=async()=>{setNotice('Retraining…');try{const {data}=await api.post('/categorization/retrain');setNotice(`Model updated using ${data.corrections_used} corrections · F1 ${Math.round(data.metrics.f1*100)}%`);load();}catch{setNotice('Retraining could not be completed.');}};
  return <><PageHeader eyebrow="LEDGER" title="Transactions" description="Add money movements in two quick steps." action={<div className="header-actions"><button className="secondary" onClick={retrain}><RefreshCw size={16}/>Retrain model</button><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>Quick add</button></div>}/>{notice?<div className="success">{notice}</div>:null}{error?<div className="error">{error}</div>:null}<article className="panel table-panel">{items.length?<div className="table"><div className="table-row head"><span>Description</span><span>Category</span><span>Date</span><span>Amount</span><span/></div>{items.map(item=>{const config=categoryMap.get(item.category);const Icon=config?.icon;return <div className="table-row" key={item.id}><span><strong>{item.description}</strong><small title={item.explanation}><Info size={11}/> {item.category_overridden?'User corrected':`${item.categorization_source.replace('_',' ')} · ${Math.round(item.confidence*100)}%`}{item.is_recurring?' · Recurring':''}</small></span><span className="category-tag" style={{'--category':config?.color,'--category-soft':config?.soft}}>{Icon?<Icon/>:null}{item.category}</span><span>{item.occurred_on}</span><span className={item.kind}>{item.kind==='income'?'+':'−'}{money(item.amount,item.currency)}</span><button className="icon-button" onClick={()=>remove(item.id)} aria-label={`Delete ${item.description}`}><Trash2 size={16}/></button></div>})}</div>:<Empty>No transactions yet. Add your first income or expense.</Empty>}</article>{open?<QuickEntry initialKind={requestedKind||'expense'} onClose={closeEntry} onCreated={load}/>:null}</>;
}
